Add files via upload

diff --git a/xmlparse b/xmlparse
--- a/xmlparse
+++ b/xmlparse
@@ -1,12 +1,13 @@
-#!/usr/bin/env bash
-gVersion=0.06
-gStamped=201124
+#!/bin/bash
+gVersion=0.07
+gStamped=201213
 #
 #	xmlparse (c) 2020 Akua Corp
 #
 #	License: Public Domain
 #
 #	History
+#	007	GLK	201213	Support -e for current behaviour, compress paths with . matching parent component
 #	006	GLK	201124	Support array indexing on by default, -a to toggle
 #	005	GLK	201121	Support multiple inputs and file or URL as argument
 #	004	GLK	201120	Show Usage if no stdin and no args
@@ -29,6 +30,8 @@ SUFFIX=''		# Only print if value has this suffix
 NEXTS=0			# Number of MATCH lines to print after SUFFIX is hit (e.g. to include following html line after jpg matches)
 NEXTC=0			# This is set to NEXTS when SUFFIX matches
 ONLYVALUE=0		# No tag path: prefix
+EXPAND=0		# Expanded full paths per line vs . per matching component
+OUTXML=0		# Output XML again (after edits presumably)
 
 # Global current tag in process
 ENTITY=''	# TAG[ prop1=2][ prop3=4][/]
@@ -36,7 +39,8 @@ CONTENT=''	# Text between TAG ...> and <
 TAG=''		# TAG of entity e.g. <TAG prop=1 prop2=3>
 PROP=''		# properties of TAG
 SINGLET=0	# Is the tag a singlet (ends with /> like img, link)
-
+LASTTAG=''	# Last tag output (to compress path)
+DEPTH=0		# How deep into the hierarchy are we?
 
 Msg()
  {
@@ -74,7 +78,7 @@ ReadXmlTag()
 	PROP="${PROP%[[:space:]]}"		# Dangling space in singlet
 	TAG="${TAG%%[[:space:]]*}"		# Space separator after TAG?
 	[ "$PROP" = "$TAG" ] && PROP=''
-	[ $BASH_VERSINFO -gt 3 ] && TAG="${TAG,,*}"				# ... lower case all tags for match - fails on Darwin's bash 3.x
+	[ $BASH_VERSINFO -gt 3 ] && TAG="${TAG,,*}" || TAG=$(echo "$TAG" | tr '[:upper:]' '[:lower:]')				# ... lower case all tags for match - fails on Darwin's bash 3.x
 	return $err
  }
 
@@ -103,7 +107,7 @@ PrintLine()
 	fi
 
 	if [ -n "$val" -o $IGNOREBLANK -eq 0 ]; then
-		[ $ONLYVALUE -eq 0 ] && PrintField "$tag:" "$val" || echo "$val"
+		[ $ONLYVALUE -eq 0 ] && PrintField "$tag" "$val" || echo "$val"
 	fi
 
 	[ $ONLYFIRST -eq 1 -a -n "$MATCH$SUFFIX" ] && exit 0 || ONLYFIRST=$(($ONLYFIRST - 1))
@@ -118,16 +122,58 @@ PrintTag()
 
 	path="$1"
 	shift
+	[ $OUTXML -ne 0 ] && path="${path##*/}"
 	for i in "$@"; do
 		DbgMsg "PROP: ($i) ($path) ($PROP)"
-		p="${i%%=*}"	# Split property from value
-		v="${i#*=}"
-		v="${v#\"}"		# Chop off quoting
-		v="${v%\"}"
-		v="${v#\'}"
-		v="${v%\'}"
-		PrintLine "$path.$p" "$v"
+		if [ $OUTXML -eq 0 ]; then
+			p="${i%%=*}"	# Split property from value
+			v="${i#*=}"
+			v="${v#\"}"		# Chop off quoting
+			v="${v%\"}"
+			v="${v#\'}"
+			v="${v%\'}"
+			PrintLine "$path.$p" "$v"
+		else
+			path="${path} $i"
+		fi
 	done
+	[ $OUTXML -ne 0 ] && PrintLine "$path" 
+ }
+
+
+CompressTag()
+ {
+	local	a n p q s r
+	local	t="$1"
+
+	OUT="$t"
+
+	a="$LASTTAG";	LASTTAG="$t"
+	n=''
+
+	s="${t#/}"
+	[ "$t" != "$s" ] && t="$s" && s='/'
+
+	r="${a#/}"
+	[ "$a" != "$r" ] && a="$r" && r='/'
+
+	[ "$r" != "$s" ] && return 0
+
+	while [ -n "$a" -a -n "$t" ]; do
+		p="${a%%/*}";	a="${a#*/}"
+		[ "$p" = "$a" ] && a=''
+		q="${t%%/*}";	t="${t#*/}"
+		[ "$q" = "$t" ] && t=''
+
+		if [ "$q" = "$p" ]; then
+			n="${n}."
+		else
+			n="$n/$q"
+			[ -n "$t" ] && n="$n/$t" && t=''
+		fi
+	done
+
+	OUT="$n$t"
  }
 
 
@@ -147,7 +193,16 @@ PrintField()
 	done
 
 	# Compress some tag path items - e.g. dict/key to %
-	echo "${tag}${l# }"
+	if [ $EXPAND -eq 0 -a $OUTXML -eq 0 ]; then
+		CompressTag "$tag"
+		tag="$OUT"
+	fi
+	if [ $OUTXML -eq 0 ]; then
+		echo "${tag}:${l# }"
+	else
+		for ((l=$DEPTH; l>0; l--)); do printf "\t"; done
+		echo "<$tag>${l# }</$tag>"
+	fi
  }
 
 
@@ -157,11 +212,13 @@ FlattenXml()
 
 	kc=''
 	last=''									# Last tag encountered (to see if we close it with next tag)
-	depth="$1"								# Depth inside hierarchy of tags
+	depth=$1								# Depth inside hierarchy of tags
 	path="$2"								# Path to current processing
 	endt="$3"								# Close tag if not last path item
 	idx=$4									# 0 or Array Index number
 	[ -z "$endt" ] && endt="${path##*/}"	# End when we hit this close tag
+
+	DEPTH=$depth							# For XML output indendation
 
 	while ReadXmlTag; do
 		if [ $SINGLET -ne 0 ]; then
@@ -269,11 +326,11 @@ DoXML()
 	while [ "$TAG" != '?xml' ]; do
 		ReadXmlTag || exit 0	# XML header
 	done
-	PrintLine "$TAG" "${ENTITY#*[[:space:]]}"
+	PrintTag "${TAG#?}" ${PROP%?} # "${ENTITY#*[[:space:]]}"
 
 	# Next tag is singlet by XML definition; RSS Feeds don't have !doctype - they have feed
 	ReadXmlTag || exit 0
-	PrintLine "$TAG" "${ENTITY#*[[:space:]]}"
+	PrintLine "${TAG#!}" "${ENTITY#*[[:space:]]}"
 
 	FlattenXml 0 ''	'' 0 # Start at the top tag
  }
@@ -310,6 +367,7 @@ Usage()
 	-b	Ignore blank lines toggle (default ON)
 	-c	Increase rawness content fields (parsed as XML -> HTML -> raw)
 	-d	Increase verbosity
+	-e	Expand full paths (vs compressed . for each matching component to parent
 	-f	Stop parsing after nth match (see -m) per stream. Can specify multiple for multiple matches.
 	-h	Ignore search for ?xml tag to start (e.g. parse HTML)
 	-k	Toggle flatten key tag into path - key/val couplets as path/key/name/type:value
@@ -318,6 +376,7 @@ Usage()
 	-q	Do not prefix each line with /path: - just value
 	-s	Suffix match - match backside (e.g. .jpg)
 	-t	Ignore content layout tags like tables, divs, spans
+	-x	Output XML ... work in progress
 
 	or - cat file.xml | $b ...
 
@@ -338,6 +397,7 @@ while [ -n "$1" ]; do
 	  '-b') IGNOREBLANK=$((1 - $IGNOREBLANK))	;;
 	  '-c') RAWCONTENT=$((1 + $RAWCONTENT))		;;	# Rawness of HTML ouput (parsed, HTML, raw)
 	  '-d')	DEBUG=$((1 + $DEBUG))				;;
+	  '-e')	EXPAND=$((1 + $EXPAND))				;;	# Expand output from compressed -> paths -> XML (XML not yet done)
 	  '-f')	ONLYFIRST=$((1 + $ONLYFIRST))		;;	# Return after finding first MATCH (-m)
 	  '-h')	IGNOREXML=$((1 - $IGNOREXML))		;;	# Allow HTML?
 	  '-k')	FLATKEY=$((1 - $FLATKEY))			;;	# Toggle flatten keys in dicts
@@ -346,6 +406,7 @@ while [ -n "$1" ]; do
 	  '-q') ONLYVALUE=$((1 - $ONLYVALUE))		;;	# No path prefix
 	  '-s')	SUFFIX="$2"; shift					;;	# Only print lines whose value ends with SUFFIX (e.g. .jpg)
 	  '-t') IGNORELAYOUT=$((1 - $IGNORELAYOUT))	;;	# Ignore content layout
+	  '-x')	OUTXML=$((1 + $OUTXML))				;;	# Output XML again
 	  '-?')	Usage; exit 0						;;
 	  -*)	Msg "Unknown option: $1"			;;
 	  *)	URL="$URL
